FROM node:22-alpine
WORKDIR /app
# Gerekli sistem paketleri (e.g. openssl for Prisma)
RUN apk add --no-cache openssl
COPY package*.json ./
RUN npm install
# Prisma schema dosyasını kopyalayıp istemciyi oluşturalım
COPY prisma ./prisma
RUN npx prisma generate
# Code will be mounted via volume
CMD ["npm", "run", "start:dev"]
